-- 1. Create the database
CREATE DATABASE IF NOT EXISTS DB_NAME;

--Use th database
USE DB_NAME;

-- 2. Create the table
CREATE TABLE IF NOT EXISTS TABLE_NAME (
    ACCNO INT PRIMARY KEY,
    NAME VARCHAR(50),
    BALANCE INT,
    MOB CHAR(10)
);

